name: CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up CMake
      uses: lukka/get-cmake@v3

    - name: Install vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        ./vcpkg/bootstrap-vcpkg.sh

    - name: Install dependencies
      run: |
        ./vcpkg/vcpkg install gtest

    - name: Build
      run: cd hra_tax_exemption && mkdir build && cd build && cmake .. && make

    - name: Run tests
      run: ctest --test-dir build