name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up CMake
      uses: lukka/get-cmake@latest

    - name: Install vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        ./vcpkg/bootstrap-vcpkg.sh

    - name: Install dependencies
      run: |
        ./vcpkg/vcpkg install gtest

    - name: debug
      run: pwd && ls -la

    - name: change directory
      run: cd hra_tax_exemption && ls -la

    - name: call cmake
      run: cmake .
    
    - name: call make
      run: make

    - name: Run tests
      run: ctest --test-dir build